#!/usr/bin/env bash
# Generate .env from $HOME defaults if it doesn't already exist.
# Run once before `podman compose run --rm finetune`.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repo_root/.env"

if [[ -f "$env_file" ]]; then
    echo "$env_file already exists — leaving it alone." >&2
    exit 0
fi

cat > "$env_file" <<EOF
# Auto-generated by scripts/setup-env.sh from \$HOME=$HOME
# Edit any value below to override the default.

# ── GPU ──────────────────────────────────────────────────────────────────────
HIP_VISIBLE_DEVICES=0
TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
# HSA_OVERRIDE_GFX_VERSION=10.3.0   # RDNA2 (RX 6000)
# HSA_OVERRIDE_GFX_VERSION=11.0.0   # RDNA3 (RX 7000)

# ── paths ────────────────────────────────────────────────────────────────────
LISTENR_HOST_DATA=$HOME/.listenr
LISTENR_HOST_DATASET=$HOME/listenr_dataset
LISTENR_HOST_FINETUNE=$HOME/listenr_finetune
LISTENR_HOST_CONFIG=$HOME/.config/listenr
LISTENR_HOST_MERGED=$HOME/listenr_merged
HF_CACHE=$HOME/.cache/huggingface
EOF

echo "Wrote $env_file"
